name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  security-events: write

jobs:
  frontend-build:
    uses: ./.github/workflows/frontend-build.yml
    with:
      node_version: '22.x'

  apphost-build:
    uses: ./.github/workflows/apphost-build.yml

  integration-test:
    needs:
      - frontend-build
      - apphost-build
    uses: ./.github/workflows/integration.yml
    with:
      node_version:  '22.x'

  security-scan:
    uses: ./.github/workflows/security-scan.yml
    with:
      node_version:  '22.x'
